# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [32]:
import pandas as pd
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, fbeta_score, confusion_matrix, balanced_accuracy_score

## Regression Model Evaluation

In [2]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

/home/eduardo/anaconda3/envs/Ironhack/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Calif

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [18]:
linreg= LinearRegression()
linreg.fit(X,y)
y_train_pred=linreg.predict(X_train)
y_test_pred=linreg.predict(X_test)

## 3. Calculate and print R-squared for both the training and the testing set.

In [20]:
print('R2 - Coeficiente de Determinacion', metrics.r2_score(y_train, y_train_pred))
print('R2 - Coeficiente de Determinacion', metrics.r2_score(y_test, y_test_pred))

R2 - Coeficiente de Determinacion 0.7471031233757379
R2 - Coeficiente de Determinacion 0.7121332359492607


## 4. Calculate and print mean squared error for both the training and the testing set.

In [23]:
print('RMSE - Raiz Error Cuadratico Medio', np.sqrt(metrics.mean_squared_error(y_train, y_train_pred)))
print('RMSE - Raiz Error Cuadratico Medio', np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))

RMSE - Raiz Error Cuadratico Medio 4.613486155726082
RMSE - Raiz Error Cuadratico Medio 4.9308410731942915


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [24]:
print('MAE - Error Medio Absoluto', metrics.mean_absolute_error(y_train, y_train_pred))
print('MAE - Error Medio Absoluto', metrics.mean_absolute_error(y_test, y_test_pred))

MAE - Error Medio Absoluto 3.274979470104384
MAE - Error Medio Absoluto 3.2545576116998762


## Classification Model Evaluation

In [25]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [28]:
logreg= LogisticRegression()
logreg.fit(X,y)
y_train_pred=logreg.predict(X_train)
y_test_pred=logreg.predict(X_test)

/home/eduardo/anaconda3/envs/Ironhack/lib/python3.8/site-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/eduardo/anaconda3/envs/Ironhack/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## 8. Calculate and print the accuracy score for both the training and the testing set.

In [41]:
print(accuracy_score(y_train,y_train_pred))
print(accuracy_score(y_test,y_test_pred))

0.9833333333333333
0.9333333333333333


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [42]:
print(balanced_accuracy_score(y_train,y_train_pred))
print(balanced_accuracy_score(y_test,y_test_pred))

0.9830979888746256
0.9444444444444445


## 10. Calculate and print the precision score for both the training and the testing set.

In [49]:
print(precision_score(y_train,y_train_pred, average='macro'))
print(precision_score(y_test,y_test_pred,average='macro'))

0.9830979888746256
0.9393939393939394


## 11. Calculate and print the recall score for both the training and the testing set.

In [48]:
print(recall_score(y_train,y_train_pred, average='macro'))
print(recall_score(y_test,y_test_pred, average='macro'))

0.9830979888746256
0.9444444444444445


## 12. Calculate and print the F1 score for both the training and the testing set.

In [52]:
print(f1_score(y_train,y_train_pred, average='macro'))
print(f1_score(y_test,y_test_pred, average='macro'))

0.9830979888746256
0.9363636363636364


## 13. Generate confusion matrices for both the training and the testing set.

In [55]:
print(confusion_matrix(y_train,y_train_pred))
print(confusion_matrix(y_test,y_test_pred))

[[41  0  0]
 [ 0 37  1]
 [ 0  1 40]]
[[ 9  0  0]
 [ 0 10  2]
 [ 0  0  9]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.